cloud:
  aws:
    credentials:
      access-key: { access-key }
      secret-key: { secret-key }
    region:
      static: { region }
    stack:
      auto: false

application:
  bucket:
    name: { bucket-name }

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9090